name: "Build Meu Egresso Front Main"
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Create .env
        working-directory: ./frontend/
        run: |
          echo VITE_API_URL_LOCAL=${{ vars.VITE_API_URL_LOCAL }} > .env 
          echo DOMAIN_APPLICATION=${{ vars.DOMAIN_APPLICATION }} >> .env
          echo VITE_URL_ENDERECOS=${{ vars.VITE_URL_ENDERECOS }} >> .env

      - name: Build the Docker image
        working-directory: ./frontend/
        run: docker build . --file docker/Dockerfile --tag alverad/meu-egresso-front:stable

      - name: Docker Push
        run: docker push alverad/meu-egresso-front:stable
